<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="CQRS\OrderItemWarehouses\Commands\" />
    <Folder Include="CQRS\ProductWarehouses\Commands\" />
    <Folder Include="Generators\" />
    <Folder Include="Models\ViewModels\" />
    <Folder Include="Validators\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="10.0.9" />
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.28" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TTERP.Domain\TTERP.Domain.csproj" />
    <ProjectReference Include="..\TTERP.Shared\TTERP.Shared.csproj" />
  </ItemGroup>

</Project>
