<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="CQRS\Employees\Commands\" />
    <Folder Include="CQRS\Employees\Handlers\" />
    <Folder Include="CQRS\Employees\Queries\" />
    <Folder Include="CQRS\Categories\Commands\" />
    <Folder Include="CQRS\Categories\Handlers\" />
    <Folder Include="CQRS\Categories\Queries\" />
    <Folder Include="CQRS\Customers\Commands\" />
    <Folder Include="CQRS\Customers\Handlers\" />
    <Folder Include="CQRS\Customers\Queries\" />
    <Folder Include="CQRS\Invoices\Commands\" />
    <Folder Include="CQRS\Invoices\Handlers\" />
    <Folder Include="CQRS\Invoices\Queries\" />
    <Folder Include="CQRS\Materials\Commands\" />
    <Folder Include="CQRS\Materials\Handlers\" />
    <Folder Include="CQRS\Materials\Queries\" />
    <Folder Include="CQRS\Notifications\Commands\" />
    <Folder Include="CQRS\Notifications\Handlers\" />
    <Folder Include="CQRS\Notifications\Queries\" />
    <Folder Include="CQRS\OrderItems\Commands\" />
    <Folder Include="CQRS\OrderItems\Handlers\" />
    <Folder Include="CQRS\OrderItems\Queries\" />
    <Folder Include="CQRS\ParameterDefinitions\Commands\" />
    <Folder Include="CQRS\ParameterDefinitions\Handlers\" />
    <Folder Include="CQRS\ParameterDefinitions\Queries\" />
    <Folder Include="CQRS\Teams\Commands\" />
    <Folder Include="CQRS\Teams\Handlers\" />
    <Folder Include="CQRS\Teams\Queries\" />
    <Folder Include="CQRS\TeamManagers\Commands\" />
    <Folder Include="CQRS\TeamManagers\Handlers\" />
    <Folder Include="CQRS\TeamManagers\Queries\" />
    <Folder Include="CQRS\Titles\Commands\" />
    <Folder Include="CQRS\Titles\Handlers\" />
    <Folder Include="CQRS\Titles\Queries\" />
    <Folder Include="CQRS\TaskAssignments\Commands\" />
    <Folder Include="CQRS\TaskAssignments\Handlers\" />
    <Folder Include="CQRS\TaskAssignments\Queries\" />
    <Folder Include="CQRS\Payments\Commands\" />
    <Folder Include="CQRS\Payments\Handlers\" />
    <Folder Include="CQRS\Payments\Queries\" />
    <Folder Include="CQRS\Roles\Commands\" />
    <Folder Include="CQRS\Roles\Handlers\" />
    <Folder Include="CQRS\Roles\Queries\" />
    <Folder Include="CQRS\Suppliers\Commands\" />
    <Folder Include="CQRS\Suppliers\Handlers\" />
    <Folder Include="CQRS\Suppliers\Queries\" />
    <Folder Include="CQRS\Supplies\Commands\" />
    <Folder Include="CQRS\Supplies\Handlers\" />
    <Folder Include="CQRS\Supplies\Queries\" />
    <Folder Include="CQRS\Tasks\Commands\" />
    <Folder Include="CQRS\Tasks\Handlers\" />
    <Folder Include="CQRS\Tasks\Queries\" />
    <Folder Include="CQRS\SupplierMaterials\Commands\" />
    <Folder Include="CQRS\SupplierMaterials\Handlers\" />
    <Folder Include="CQRS\SupplierMaterials\Queries\" />
    <Folder Include="CQRS\Products\Commands\" />
    <Folder Include="CQRS\Products\Handlers\" />
    <Folder Include="CQRS\Products\Queries\" />
    <Folder Include="CQRS\ParameterValues\Commands\" />
    <Folder Include="CQRS\ParameterValues\Handlers\" />
    <Folder Include="CQRS\ParameterValues\Queries\" />
    <Folder Include="CQRS\Announcements\Commands\" />
    <Folder Include="CQRS\Announcements\Handlers\" />
    <Folder Include="CQRS\Announcements\Queries\" />
    <Folder Include="CQRS\Orders\Commands\" />
    <Folder Include="CQRS\Orders\Handlers\" />
    <Folder Include="CQRS\Orders\Queries\" />
    <Folder Include="Models\DTOs\" />
    <Folder Include="Models\ViewModels\" />
    <Folder Include="ServiceInterfaces\" />
    <Folder Include="Validators\" />
  </ItemGroup>

</Project>
