<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Generators\**" />
    <EmbeddedResource Remove="Generators\**" />
    <None Remove="Generators\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CQRS\Authentications\Commands\" />
    <Folder Include="CQRS\ExchangeRates\Commands\" />
    <Folder Include="CQRS\ProductionProgresses\Queries\" />
    <Folder Include="CQRS\Towns\Commands\" />
    <Folder Include="CQRS\Districts\Commands\" />
    <Folder Include="CQRS\PostalCodes\Commands\" />
    <Folder Include="CQRS\PostalCodes\Handlers\" />
    <Folder Include="CQRS\PostalCodes\Queries\" />
    <Folder Include="CQRS\Neighborhoods\Commands\" />
    <Folder Include="CQRS\Cities\Commands\" />
    <Folder Include="CQRS\Countries\Commands\" />
    <Folder Include="CQRS\OrderItemWarehouses\Commands\" />
    <Folder Include="Models\DTOs\PostalCodes\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="CQRS\ProductWarehouses\Queries\GetWarehousesByProductIdQuery.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Mapster" Version="10.0.9" />
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.28" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TTERP.Domain\TTERP.Domain.csproj" />
    <ProjectReference Include="..\TTERP.Shared\TTERP.Shared.csproj" />
  </ItemGroup>

</Project>
